package jp.co.momogo.databuilder.staticdata

val japaneseRestaurantDescriptionNameList = listOf(
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "japan test",
    "japan test",
    "japan test",
    "japan test",
    "japan test",
    "japan test",
    "japan test",
    "japan test",
    "japan test",
)
val westernRestaurantDescriptionNameList = listOf(
    "western test",
    "western test",
    "western test",
    "western test",
    "western test",
    "western test",
    "western test",
    "western test",
    "western test",
    "western test",
)
val koreanRestaurantDescriptionNameList = listOf(
    "korean test",
    "korean test",
    "korean test",
    "korean test",
    "korean test",
    "korean test",
    "korean test",
    "korean test",
    "korean test",
    "korean test",
)
val chineseRestaurantDescriptionNameList = listOf(
    "chinese test",
    "chinese test",
    "chinese test",
    "chinese test",
    "chinese test",
    "chinese test",
    "chinese test",
    "chinese test",
    "chinese test",
    "chinese test",
)
val seafoodRestaurantDescriptionNameList = listOf(
    "seafood test",
    "seafood test",
    "seafood test",
    "seafood test",
    "seafood test",
    "seafood test",
    "seafood test",
    "seafood test",
    "seafood test",
    "seafood test",
)
val ramenRestaurantDescriptionNameList = listOf(
    "ramen test",
    "ramen test",
    "ramen test",
    "ramen test",
    "ramen test",
    "ramen test",
    "ramen test",
    "ramen test",
    "ramen test",
    "ramen test",
)
val friedRestaurantDescriptionNameList = listOf(
    "fried test",
    "fried test",
    "fried test",
    "fried test",
    "fried test",
    "fried test",
    "fried test",
    "fried test",
    "fried test",
    "fried test",
)
val skewersRestaurantDescriptionNameList = listOf(
    "skewers test",
    "skewers test",
    "skewers test",
    "skewers test",
    "skewers test",
    "skewers test",
    "skewers test",
    "skewers test",
    "skewers test",
    "skewers test",
)
val noodleRestaurantDescriptionNameList = listOf(
    "noodle test",
    "noodle test",
    "noodle test",
    "noodle test",
    "noodle test",
    "noodle test",
    "noodle test",
    "noodle test",
    "noodle test",
    "noodle test",
)
val curryRestaurantDescriptionNameList = listOf(
    "curry test",
    "curry test",
    "curry test",
    "curry test",
    "curry test",
    "curry test",
    "curry test",
    "curry test",
    "curry test",
    "curry test",
)
val dessertRestaurantDescriptionNameList = listOf(
    "dessert test",
    "dessert test",
    "dessert test",
    "dessert test",
    "dessert test",
    "dessert test",
    "dessert test",
    "dessert test",
    "dessert test",
    "dessert test",
)